### ISSUE TITLE
Volume boost is disabled after each reboot on Gnome 3.18

### ISSUE THREAD

**Issue by elmagio** [aleho/gnome-shell-volume-mixer#46] opened 2016-04-25 12:21 UTC
I have to go in extensions settings and uncheck/recheck the corresponding box for it to work again. It happened every once in a while in Gnome 3.16 on Ubuntu 15.10, but now it's after every logout.

**Comment by aleho** [comment] 2016-04-25 13:02
Duplicate of #29.
Nothing I can do about it. Doesn't seem to happen to me as often any more on 3.20 though.

**Closed by aleho** 2016-04-25 13:02 UTC

**Comment by elmagio** [comment] 2016-06-29 10:43
I get that it can't be fixed, but after I thought about it, I wondered if maybe you could give me the command used to activate/deactivate volume boost through your extension, so that I could make a script run that a few seconds after login automatically (or even to activate when I need to through the terminal)? Would be easier to do than going through the Tweak Tool and the extension settings.
