### ISSUE TITLE
OSD with volume boost maxes at 100% after some time

### ISSUE THREAD

**Issue by jsquaredz** [aleho/gnome-shell-volume-mixer#52] opened 2016-06-09 23:13 UTC
When I activate volume boost in the volume mixer settings, the OSD correctly shows and allows volume up to 153%.  After some time (not sure if its a suspend or hibernate thing), the volume control reverts to the non overboosted control.  

The only way to get it back is to go into the volume mixer settings, flip the switch to shut off overboost, then flip it back on, and the OSD and volume control will go back to allowing overboost.

**Comment by aleho** [comment] 2016-09-18 07:51
Duplicate of #29

**Closed by aleho** 2016-09-18 07:51 UTC
