### ISSUE TITLE
Allow switching between output ports

### ISSUE THREAD

**Issue by Elinvention** [aleho/gnome-shell-volume-mixer#124] opened 2020-08-02 20:03 UTC
First of all, thank you very much for this extension.
I'd like to be able to switch between output ports too. This what I mean, using pavucontrol:
![image](https://user-images.githubusercontent.com/5737945/89131260-a5214900-d50b-11ea-9ed5-7c7bace9a610.png)

**Comment by aleho** [comment] 2021-01-24 15:45
Duplicate of #20?

**Comment by Elinvention** [comment] 2021-01-24 16:01
I don't think so. I don't get what that issue is about, but he is talking about usb headsets (a different pulseaudio sink). I'd like to switch between front and rear output port of the same pulseaudio sink without having to unplug my headphones.

**Comment by aleho** [comment] 2021-01-25 09:32
"Duplicate" is wrong, but if this feature is to be implemented it needs a general rewrite / enhancement in the area of switching. Not only output ports (which, as far as I know, is hard to get right from an extension, because a few of the bindings are not there and crash the shell), but also input ports or inactive sinks, etc.

**Comment by Elinvention** [comment] 2021-01-25 17:39
However I have been using this other extension https://github.com/kgshank/gse-sound-output-device-chooser with success as i can switch between output ports. However I like your extension more because of the additional features and the better UI.

**Comment by stuaxo** [comment] 2021-01-29 14:48
@aleho is there an upstream bug for the missing bindings / bits that crash the shell ?

If not it might be worth opening one, though I guess all bets might be off until GNOME based on gtk 4 is released ?

**Comment by aleho** [comment] 2021-02-04 11:25
There were a couple bug reports, IIRC.

**Comment by schrej** [comment] 2021-12-08 08:25
I has been suggested to merge both extensions into one, maybe it's worth to actually attempt that: https://github.com/kgshank/gse-sound-output-device-chooser/issues/100

**Comment by aleho** [comment] 2021-12-08 10:12
I don't know. The author of that extension seems to have copy/pasted from here (e.g. the Python helper uses the exact same local variable names, that's too much of a coincidence in my opinion) and claims he's the author. That's not how collaboration works.

**Comment by aleho** [comment] 2022-09-05 09:33
Sorry, I'm not going to fix any issues for older versions and reevaluate the use-case for this extension for 43.

**Closed by aleho** 2022-09-05 09:33 UTC
Labels: help wanted
