### ISSUE TITLE
Does not work with Gnome 3.36

### ISSUE THREAD

**Issue by T8xi** [aleho/gnome-shell-volume-mixer#114] opened 2020-03-23 06:10 UTC
I'm running Arch Linux with GNOME 3.36 and tried to install the extension via GNOME Extensions Website, which results in an error.

Again GNOME manages to break stuff for many extension developers. Sadly I don't have the proper skills to dig deeper into the issue. I tried to get something out of the journalctl but there is no error if I enable the extension via command line.
So I'm uncertain if this occurs because there is no 3.36 release on the extension page or if there is indeed an error in the extension itself.

So if you have time, could you investigate it? If you tell me how I can provide you with more details I would be glad to help!

**Comment by aleho** [comment] 2020-03-23 06:30
Yeah, there are multiple issues the way Gnome Shell is developed. Without looking the the code and commits I wouldn't be able to even find out what might be wrong, because the error log is cryptic at best and there's no "breaking changes" for extension developers.

Apart from breaking almost every release they also removed restrictions for newer extensions. So you now can download a broken extension that was written for 3.34 if you're on 3.36 because "we don't break anything and most extensions still work". Which is laughable at best because of all the extensions I use besides this one not a single one survived a single update in the last 5 years. :man_facepalming:

Thanks for your report anyway, but I think this is a duplicate of #111. Could you try installing the latest release manually https://github.com/aleho/gnome-shell-volume-mixer/releases/download/3.36.0/shell-volume-mixer-3.36.0.zip?

**Comment by rdehouss** [comment] 2020-03-23 13:04
Hi !

I just tried to install it with `unzip Downloads/shell-volume-mixer-3.36.0.zip -d ~/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/` but the extension is still marked in error.
Although, I can get the "settings" window, but it does not change the volume mixer in the status panel.

If you want to make other tests, I can provide you the results.
I'm running Manjaro :)

**Comment by thepasto** [comment] 2020-03-23 22:33
It works fine for me on arch linux! Thanks

**Comment by AlexWayfer** [comment] 2020-03-23 23:48
> Yeah, there are multiple issues the way Gnome Shell is developed. Without looking at the code and commits I wouldn't be able to even find out what might be wrong, because the error log is cryptic at best and there's no "breaking changes" for extension developers.
> 
> Apart from breaking almost every release they also removed restrictions for newer extensions. So you now can download a broken extension that was written for 3.34 if you're on 3.36 because "we don't break anything and most extensions still work". Which is laughable at best because of all the extensions I use besides this one not a single one survived a single update in the last 5 years. 

3.36 is most breaking for extensions in my memory.

**Comment by T8xi** [comment] 2020-03-24 05:43
@rdehouss I would rather delete the extension you installed via the extension website and then install it via zip.
I tried it right now and **it works** on Arch Linux.

```
unzip ~/Downloads/shell-volume-mixer-3.36.0.zip -d ~/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/

gnome-extensions enable shell-volume-mixer@derhofbauer.at
```
You may have to reload your shell `Alt+F2` and type `r` hit enter

**Closed** 2020-03-24 19:13 UTC
Labels: duplicate

**Comment by aleho** [comment] 2020-03-25 09:19
Great, thanks for testing!

(I'll spin up a Manjaro and check soon-ish)

**Comment by rdehouss** [comment] 2020-04-07 07:01
Yep, I confirm it's working on Manjaro as well.
