### ISSUE TITLE
Long list of sources make UI unusable

### ISSUE THREAD

**Issue by nachokb** [aleho/gnome-shell-volume-mixer#78] opened 2017-11-29 22:50 UTC
I usually find Chrome or Firefox create a long list of audio sources (particularly when using many tabs after many days), and make the app list grow beyond the screen.

This causes some apps to be inaccessible, and also makes the exapandable device chooser unable to show all devices.

![volume-mixer-sinks](https://user-images.githubusercontent.com/17967/33403098-c70470ae-d53d-11e7-99a6-5f879a2dde36.png)

Possible solutions I can think about:

* group sources by app or title (somehow detecting different Firefox processes as the same app):
  * each group would be collapsed initially, but also scrollable;
* make the whole container scrollable;

Any opinions?

**Comment by aleho** [comment] 2017-11-30 12:07
There's no way to get application details of a stream that I'm aware of (at least last time I checked).

Anyway, this seems to be a duplicate of #40 and should be fixed already (look at current the screenshots). You don't seem to be using the latest version judging by you screenshot.

**Closed by aleho** 2017-11-30 12:07 UTC
