### ISSUE TITLE
Won’t start on Archlinux GNOME Shell 3.20.1

### ISSUE THREAD

**Issue by Wabuo** [aleho/gnome-shell-volume-mixer#49] opened 2016-04-29 16:32 UTC
That's what I got out of `journalctl /usr/bin/gnome-shell -f -o cat`.
If you need somthing from me, just ask.

```sh
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Gjs-Message: JS LOG: Failed to launch ibus-daemon: Kindprozess »ibus-daemon« konnte nicht ausgeführt werden (Datei oder Verzeichnis nicht gefunden)
Gjs-Message: JS LOG: Failed to add search provider /usr/share/gnome-shell/search-providers/org.gnome.bijiben-search-provider.ini: TypeError: appInfo is null
Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
Gjs-Message: JS LOG: Extension "shell-volume-mixer@derhofbauer.at" had error: Error: No signal 'stream-changed' on object 'GvcMixerControl'
Gjs-Message: JS LOG: loading default theme (Adwaita)
(gnome-shell:962): Gjs-WARNING **: JS ERROR: TypeError: this._input is undefined
VolumeMenu<._readInput@resource:///org/gnome/shell/ui/status/volume.js:296
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
(gnome-shell:962): Gjs-WARNING **: JS ERROR: TypeError: this._output is undefined
Menu<._addStream@/home/fabio/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/menu.js:162
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
Menu<._streamAdded@/home/fabio/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/menu.js:173
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
(gnome-shell:962): Gjs-WARNING **: JS ERROR: TypeError: this._output is undefined
VolumeMenu<._readOutput@resource:///org/gnome/shell/ui/status/volume.js:292
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
_parent@resource:///org/gnome/gjs/modules/lang.js:131
Menu<._readOutput@/home/fabio/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/menu.js:116
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
(gnome-shell:962): Gjs-WARNING **: JS ERROR: TypeError: this._input is undefined
VolumeMenu<._readInput@resource:///org/gnome/shell/ui/status/volume.js:296
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
(gnome-shell:962): Gjs-WARNING **: JS ERROR: TypeError: this._input is undefined
VolumeMenu<._readInput@resource:///org/gnome/shell/ui/status/volume.js:296
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
VolumeMenu<._onControlStateChanged@resource:///org/gnome/shell/ui/status/volume.js:284
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
_parent@resource:///org/gnome/gjs/modules/lang.js:131
Menu<._onControlStateChanged@/home/fabio/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/menu.js:103
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
GNOME Shell started at Fri Apr 29 2016 18:18:52 GMT+0200 (CEST)

```

**Comment by aleho** [comment] 2016-04-29 20:07
Duplicate of #47

**Closed by aleho** 2016-04-29 20:07 UTC
